version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: florium_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: florium
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - florium-network

  backend:
    build:
      context: ./florium-backend
      dockerfile: Dockerfile
    container_name: florium_backend
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: florium
    depends_on:
      - postgres
    volumes:
      - ./florium-backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - florium-network

  frontend:
    build:
      context: ./florium-frontend
      dockerfile: Dockerfile
    container_name: florium_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./florium-frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - florium-network

volumes:
  postgres_data:


networks:
  florium-network:
